package pl.zajacp.investmentmanager.actionmanagement;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import pl.zajacp.investmentmanager.products.Investment;
import pl.zajacp.investmentmanager.products.SavingsAccount;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.Year;
import java.time.YearMonth;
import java.util.*;

import static java.time.temporal.ChronoUnit.DAYS;

@Service
@Transactional
public class FinanceCalcService {

    private final ActionRepository actionRepository;
    private final BigDecimal BELKA_TAX = new BigDecimal(0.81);

    public FinanceCalcService(ActionRepository actionRepository) {
        this.actionRepository = actionRepository;
    }

    public BigDecimal getInvestmentValueWithReturn(Investment product) {
        long daysValid = DAYS.between(product.getOpenDate(),
                product.getOpenDate().plusMonths(product.getMonthsValid()));

        return product.getValue().add(product.getValue().multiply(product.getInterest())
                .multiply(new BigDecimal(1.0 * daysValid / Year.of(product.getOpenDate().getYear()).length()))
                .multiply(BELKA_TAX).setScale(2, RoundingMode.HALF_UP));
    }

    public List<LocalDate> getCapitalizationDates(SavingsAccount product) {

        /*
         * Create list of dates consisting of last days of months for a whole year.
         */

        List<LocalDate> capitalizationDates = new ArrayList<LocalDate>();
        LocalDate currentDate = product.getCreated();

        for (int i = 0; i < 12; i++) {
            YearMonth yearMonth = YearMonth.from(currentDate.plusMonths(i));
            capitalizationDates.add(yearMonth.atEndOfMonth());
        }
        return capitalizationDates;
    }

    public BigDecimal getFullCapitalization(BigDecimal value, SavingsAccount product, LocalDate date) {
        return getCapitalizedProfit(value, product, date, true).multiply(BELKA_TAX);
    }

    public BigDecimal getAfterPromotionCapitalization(BigDecimal value, SavingsAccount product, LocalDate date) {
        return getCapitalizedProfit(value, product, date, false).multiply(BELKA_TAX);
    }

    private BigDecimal getCapitalizedProfit(BigDecimal value, SavingsAccount product, LocalDate date, boolean isPromotionActive) {

        BigDecimal currentInterest = isPromotionActive ? product.getInterest() : product.getInterestAboveLimit();

        BigDecimal yearFraction = new BigDecimal
                (1.0 * YearMonth.from(date).lengthOfMonth() / YearMonth.from(date).lengthOfYear());

        //equation: value*(1+(interest*yearFraction))
        BigDecimal valueWithoutLimit = value.multiply(BigDecimal.ONE.add(currentInterest.multiply(yearFraction)));

        /*following calculation is necesarry in case the value exceeded promotional account limit */

        //equation: 1-(withoutLimitValue-valueLimit)/(withoutLimitValue-value)
        BigDecimal fullProfitFraction = BigDecimal.ONE.subtract((valueWithoutLimit.subtract(product.getValueLimit())
                .divide(valueWithoutLimit.subtract(value), BigDecimal.ROUND_HALF_UP)));
        if (fullProfitFraction.compareTo(BigDecimal.ONE) > 0) {
            fullProfitFraction = BigDecimal.ONE;
        } else if (fullProfitFraction.compareTo(BigDecimal.ZERO) < 0) {
            fullProfitFraction = BigDecimal.ZERO;
        }

        //value with profit generated by main intere7st rate
        //equation: value*(1+interest/yearFraction)*fullProfitFraction
        BigDecimal fullProfitValue = value.multiply(BigDecimal.ONE.add(currentInterest.multiply(yearFraction)))
                .multiply(fullProfitFraction);

        //value with profit generated by interest rate above limit
        //equation (1-fullProfitFraction)*value*(1+interestAbove/yearFraction)
        BigDecimal limitedProfitValue = BigDecimal.ONE.subtract(fullProfitFraction)
                .multiply(value).multiply(BigDecimal.ONE.add(product.getInterestAboveLimit()));

        return fullProfitValue.add(limitedProfitValue).subtract(value);
    }


    public BigDecimal getFirstOrLastMonthCapitalization(BigDecimal value, SavingsAccount product,
                                                        LocalDate date, boolean closureMonth) {
        /*
         * Date used in first and last have to be open/close date, as days number is used for calculation.
         * All other months in between are using capitalization date.
         */
        int daysInMonth = YearMonth.from(date).lengthOfMonth();

        BigDecimal correctedProfit = null;
        BigDecimal secondMonthPart = new BigDecimal(1.0 - (1.0 * date.getDayOfMonth() / daysInMonth));

        if (closureMonth) {
            BigDecimal firstMonthPart = new BigDecimal(1.0 * date.getDayOfMonth() / daysInMonth);
            secondMonthPart = new BigDecimal(1.0 - (1.0 * date.getDayOfMonth() / daysInMonth));
            BigDecimal firstMonthPartProfit = getFullCapitalization(value, product, date).multiply(firstMonthPart);
            BigDecimal secondMonthPartProfit = getAfterPromotionCapitalization(value, product, date).multiply(secondMonthPart);
            correctedProfit = firstMonthPartProfit.add(secondMonthPart);
        } else {
            correctedProfit = getFullCapitalization(value, product, date).multiply(secondMonthPart);
        }
        return correctedProfit;
    }
    //TODO need to work as original
    public void recalculateCapitalizations(SavingsAccount product, boolean fromTodayCalculation) {
        /*
         * Recalculates all capitalization actions taking into account all withdraws and payments. Recalculates either
         * all actions for given product (with past ones), or all future actions starting from current month.
         * It divides actions into months and changes capitalization values in place, month after month.
         */
        product.setActions(actionRepository.findByProductOrderByActionDateAscAfterActionValueAsc(product));
        List<Action> actions = product.getActions();

        LocalDate currentDate = fromTodayCalculation ? LocalDate.now() : actions.get(0).getActionDate();
        BigDecimal currentValue = product.getValue();

        int currentYear = currentDate.getYear();
        int currentMonth = currentDate.getMonthValue();

        int upperBoundIndex, lowerBoundIndex = 0;

        for (int i = 0; i < actions.size(); i++) {
            int actionYear = actions.get(i).getActionDate().getYear();
            int actionMonth = actions.get(i).getActionDate().getMonthValue();

            //In case of calculation from actual date, here it omits past months
            if (fromTodayCalculation && currentMonth > actionMonth && currentYear >= actionYear) {
                lowerBoundIndex = i + 1;
                continue;
            }

            if (actions.get(i).getActionType() == ActionType.CAPITALIZATION) {
                upperBoundIndex = i;
                fixMonthlyCapitalization(product, lowerBoundIndex, upperBoundIndex, currentValue);
                System.out.println(lowerBoundIndex + " / " + upperBoundIndex);
                currentValue = actions.get(i).getAfterActionValue();
                lowerBoundIndex = i + 1;
            }
        }
        actionRepository.saveAll(actions);
    }

    public void fixMonthlyCapitalization(SavingsAccount product, int lowerMonthBound, int upperMonthBound, BigDecimal initialValue) {

        List<Action> actions = product.getActions();
        Action capitalization = actions.get(upperMonthBound);
        BigDecimal withdraws = BigDecimal.ZERO;
        BigDecimal totalValueChange = initialValue;
        BigDecimal totalCapitalization = BigDecimal.ZERO;

        for (int i = lowerMonthBound; i < upperMonthBound; i++) {
            if (actions.get(i).getActionType() != ActionType.BALANCE_CHANGE) {
                continue;
            }
            BigDecimal currentChange = actions.get(i).getBalanceChange();
            if (currentChange.compareTo(BigDecimal.ZERO) > 0) {
                //payments capitalizations
                totalCapitalization = totalCapitalization.add(getFirstOrLastMonthCapitalization
                        (currentChange, product, actions.get(i).getActionDate(), false));
            } else {
                //widthdraws capitalizations
                totalCapitalization = totalCapitalization.subtract(getFirstOrLastMonthCapitalization
                        (currentChange.abs(), product, actions.get(i).getActionDate(), false));
                withdraws = withdraws.subtract(currentChange);
            }
            totalValueChange = totalValueChange.add(currentChange);
            actions.get(i).setAfterActionValue(totalValueChange);
        }
        //rest of unchanged value capitalization
        totalCapitalization = totalCapitalization
                .add(getFullCapitalization(initialValue.subtract(withdraws), product, capitalization.getActionDate()));

        capitalization.setAfterActionValue(totalValueChange.add(totalCapitalization).setScale(2, RoundingMode.HALF_UP));

    }

    public Map<LocalDate, BigDecimal> getGain(List<Action> actions) {
        /*
         * Returns map of dates when capitalization occured with calculated gain from open date.
         * */
        Map<LocalDate, BigDecimal> gain = new LinkedHashMap<>();
        BigDecimal currentVal = actions.get(0).getAfterActionValue();

        for (int i = 1; i < actions.size(); i++) {
            Action currentAction = actions.get(i);
            if (currentAction.getActionType() == ActionType.BALANCE_CHANGE) {
                currentVal = currentVal.add(actions.get(i).getBalanceChange());
            } else if (currentAction.getActionType() == ActionType.CAPITALIZATION) {
                gain.put(currentAction.getActionDate(), currentAction.getAfterActionValue().subtract(currentVal)
                        .setScale(2, RoundingMode.HALF_UP));
            }
        }
        return gain;
    }
}